## Using part of feature of boston'houses

In [9]:
## load_package 
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## data_aalysis package
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [11]:
boston_dataset = load_boston()

In [12]:
boston_dataset.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [52]:
## test to take the max in first coordinate 
boston_dataset.data[:,0].max()

88.9762

In [20]:
## test to take the min in first coordinate 
m=boston_dataset.data[:,0].min()

In [24]:
(boston_dataset.data[:,0]-m)/(M-m)

array([0.00000000e+00, 2.35922539e-04, 2.35697744e-04, 2.92795719e-04,
       7.05070075e-04, 2.64471527e-04, 9.21323037e-04, 1.55367187e-03,
       2.30325139e-03, 1.84017333e-03, 2.45667410e-03, 1.24929920e-03,
       9.83029313e-04, 7.00731528e-03, 7.09948131e-03, 6.98067706e-03,
       1.17748838e-02, 8.74318365e-03, 8.95123159e-03, 8.08678173e-03,
       1.39987825e-02, 9.50568889e-03, 1.37816304e-02, 1.10386796e-02,
       8.36170623e-03, 9.37643166e-03, 7.48107112e-03, 1.06715891e-02,
       8.61718595e-03, 1.11962610e-02, 1.26389965e-02, 1.51556909e-02,
       1.55296377e-02, 1.28740198e-02, 1.80566727e-02, 6.50220052e-04,
       1.02416683e-03, 8.29719002e-04, 1.89648452e-03, 2.39519262e-04,
       3.06508225e-04, 1.36135960e-03, 1.51939061e-03, 1.72013270e-03,
       1.30797074e-03, 1.85568419e-03, 2.04608571e-03, 2.50590425e-03,
       2.78240231e-03, 2.39912654e-03, 9.26268530e-04, 4.16433067e-04,
       5.31415800e-04, 4.88817114e-04, 8.18254447e-05, 7.63179629e-05,
      

In [27]:
((boston_dataset.data[:,0]-m)/(M-m)).min()

0.0

In [48]:
## 1 way using for-loop
M=list()
for i in range(0,13):
    M.append(boston_dataset.data[:,i].max())

In [62]:
## 2 second way using one-listd (calculate th max)
M=np.array([boston_dataset.data[:,i].max() for i in range(0,13)])

In [63]:
M

array([ 88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,   8.78  ,
       100.    ,  12.1265,  24.    , 711.    ,  22.    , 396.9   ,
        37.97  ])

In [64]:
## (calculate the min)
m=np.array([boston_dataset.data[:,i].min() for i in range(0,13)])

In [65]:
m

array([6.3200e-03, 0.0000e+00, 4.6000e-01, 0.0000e+00, 3.8500e-01,
       3.5610e+00, 2.9000e+00, 1.1296e+00, 1.0000e+00, 1.8700e+02,
       1.2600e+01, 3.2000e-01, 1.7300e+00])

In [76]:
## nomalization for boston_dataset.data
normali=((boston_dataset.data-m)/(M-m))

In [77]:
boston=pd.DataFrame(normali,columns=boston_date.feature_names)

In [78]:
boston['MEDV']=boston_date.target

In [79]:
boston

CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0    0.000000  0.18  0.067815   0.0  0.314815  0.577505  0.641607  0.269203   
1    0.000236  0.00  0.242302   0.0  0.172840  0.547998  0.782698  0.348962   
2    0.000236  0.00  0.242302   0.0  0.172840  0.694386  0.599382  0.348962   
3    0.000293  0.00  0.063050   0.0  0.150206  0.658555  0.441813  0.448545   
4    0.000705  0.00  0.063050   0.0  0.150206  0.687105  0.528321  0.448545   
..        ...   ...       ...   ...       ...       ...       ...       ...   
501  0.000633  0.00  0.420455   0.0  0.386831  0.580954  0.681771  0.122671   
502  0.000438  0.00  0.420455   0.0  0.386831  0.490324  0.760041  0.105293   
503  0.000612  0.00  0.420455   0.0  0.386831  0.654340  0.907312  0.094381   
504  0.001161  0.00  0.420455   0.0  0.386831  0.619467  0.889804  0.114514   
505  0.000462  0.00  0.420455   0.0  0.386831  0.473079  0.802266  0.125072   

          RAD       TAX   PTRATIO         B     LSTAT  MEDV  
0    0.000000  0.208015  0.287234  1.000000  0.089680  24.0  
1    0.043478  0.104962  0.553191  1.000000  0.204470  21.6  
2    0.043478  0.104962  0.553191  0.989737  0.063466  34.7  
3    0.086957  0.066794  0.648936  0.994276  0.033389  33.4  
4    0.086957  0.066794  0.648936  1.000000  0.099338  36.2  
..        ...       ...       ...       ...       ...   ...  
501  0.000000  0.164122  0.893617  0.987619  0.219095  22.4  
502  0.000000  0.164122  0.893617  1.000000  0.202815  20.6  
503  0.000000  0.164122  0.893617  1.000000  0.107892  23.9  
504  0.000000  0.164122  0.893617  0.991301  0.131071  22.0  
505  0.000000  0.164122  0.893617  1.000000  0.169702  11.9  

[506 rows x 14 columns]

In [104]:
boston.sort_values(by="MEDV",ascending=False).index[:20]

Int64Index([284, 226, 370, 371, 372, 373, 187, 205, 258, 196, 167, 164, 268,
            163, 162, 369, 263, 204, 234, 229],
           dtype='int64')

In [83]:
boston.corr().round(2)

CRIM    ZN  INDUS  CHAS   NOX    RM   AGE   DIS   RAD   TAX  PTRATIO  \
CRIM     1.00 -0.20   0.41 -0.06  0.42 -0.22  0.35 -0.38  0.63  0.58     0.29   
ZN      -0.20  1.00  -0.53 -0.04 -0.52  0.31 -0.57  0.66 -0.31 -0.31    -0.39   
INDUS    0.41 -0.53   1.00  0.06  0.76 -0.39  0.64 -0.71  0.60  0.72     0.38   
CHAS    -0.06 -0.04   0.06  1.00  0.09  0.09  0.09 -0.10 -0.01 -0.04    -0.12   
NOX      0.42 -0.52   0.76  0.09  1.00 -0.30  0.73 -0.77  0.61  0.67     0.19   
RM      -0.22  0.31  -0.39  0.09 -0.30  1.00 -0.24  0.21 -0.21 -0.29    -0.36   
AGE      0.35 -0.57   0.64  0.09  0.73 -0.24  1.00 -0.75  0.46  0.51     0.26   
DIS     -0.38  0.66  -0.71 -0.10 -0.77  0.21 -0.75  1.00 -0.49 -0.53    -0.23   
RAD      0.63 -0.31   0.60 -0.01  0.61 -0.21  0.46 -0.49  1.00  0.91     0.46   
TAX      0.58 -0.31   0.72 -0.04  0.67 -0.29  0.51 -0.53  0.91  1.00     0.46   
PTRATIO  0.29 -0.39   0.38 -0.12  0.19 -0.36  0.26 -0.23  0.46  0.46     1.00   
B       -0.39  0.18  -0.36  0.05 -0.38  0.13 -0.27  0.29 -0.44 -0.44    -0.18   
LSTAT    0.46 -0.41   0.60 -0.05  0.59 -0.61  0.60 -0.50  0.49  0.54     0.37   
MEDV    -0.39  0.36  -0.48  0.18 -0.43  0.70 -0.38  0.25 -0.38 -0.47    -0.51   

            B  LSTAT  MEDV  
CRIM    -0.39   0.46 -0.39  
ZN       0.18  -0.41  0.36  
INDUS   -0.36   0.60 -0.48  
CHAS     0.05  -0.05  0.18  
NOX     -0.38   0.59 -0.43  
RM       0.13  -0.61  0.70  
AGE     -0.27   0.60 -0.38  
DIS      0.29  -0.50  0.25  
RAD     -0.44   0.49 -0.38  
TAX     -0.44   0.54 -0.47  
PTRATIO -0.18   0.37 -0.51  
B        1.00  -0.37  0.33  
LSTAT   -0.37   1.00 -0.74  
MEDV     0.33  -0.74  1.00

In [105]:
### it means 6/20 is 1 in CHAS
boston[boston["CHAS"]==1].index&boston.sort_values(by="MEDV",ascending=False).index[:20]

Int64Index([163, 164, 284, 370, 371, 373], dtype='int64')

In [81]:
# set operation
set([1,34])&set([1,3])

{1}

In [82]:
from sklearn import preprocessing

In [84]:
boston_dataset1 = load_boston()
boston_normalized = preprocessing.minmax_scale(boston_dataset1.data)
boston = pd.DataFrame(boston_normalized, columns=boston_dataset1.feature_names)

boston['MEDV'] = boston_dataset1.target

In [85]:
boston

CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0    0.000000  0.18  0.067815   0.0  0.314815  0.577505  0.641607  0.269203   
1    0.000236  0.00  0.242302   0.0  0.172840  0.547998  0.782698  0.348962   
2    0.000236  0.00  0.242302   0.0  0.172840  0.694386  0.599382  0.348962   
3    0.000293  0.00  0.063050   0.0  0.150206  0.658555  0.441813  0.448545   
4    0.000705  0.00  0.063050   0.0  0.150206  0.687105  0.528321  0.448545   
..        ...   ...       ...   ...       ...       ...       ...       ...   
501  0.000633  0.00  0.420455   0.0  0.386831  0.580954  0.681771  0.122671   
502  0.000438  0.00  0.420455   0.0  0.386831  0.490324  0.760041  0.105293   
503  0.000612  0.00  0.420455   0.0  0.386831  0.654340  0.907312  0.094381   
504  0.001161  0.00  0.420455   0.0  0.386831  0.619467  0.889804  0.114514   
505  0.000462  0.00  0.420455   0.0  0.386831  0.473079  0.802266  0.125072   

          RAD       TAX   PTRATIO         B     LSTAT  MEDV  
0    0.000000  0.208015  0.287234  1.000000  0.089680  24.0  
1    0.043478  0.104962  0.553191  1.000000  0.204470  21.6  
2    0.043478  0.104962  0.553191  0.989737  0.063466  34.7  
3    0.086957  0.066794  0.648936  0.994276  0.033389  33.4  
4    0.086957  0.066794  0.648936  1.000000  0.099338  36.2  
..        ...       ...       ...       ...       ...   ...  
501  0.000000  0.164122  0.893617  0.987619  0.219095  22.4  
502  0.000000  0.164122  0.893617  1.000000  0.202815  20.6  
503  0.000000  0.164122  0.893617  1.000000  0.107892  23.9  
504  0.000000  0.164122  0.893617  0.991301  0.131071  22.0  
505  0.000000  0.164122  0.893617  1.000000  0.169702  11.9  

[506 rows x 14 columns]